### ISSUE TITLE
Unable to download due to 500 status

### ISSUE THREAD

**Issue by uvanchang** [kkdai/youtube#214]
I'm trying to download a video in this specific format and it's failing. Here's the command and the output.

```
./youtubedr download K3MhYh29jwc -q hd720
check ffmpeg is installed....
0.00 b / 0.00 b 0 % [--------------------------------------------------------------] 0s ] 0.00 b/s
1.82 MiB / 1.82 MiB 100 % [==============================================================] 0s ] 49.00 KiB/s
[m4v @ 0x5632f2d72480] Format m4v detected only with low score of 1, misdetection possible!
[m4v @ 0x5632f2d72480] Could not find codec parameters for stream 0 (Video: mpeg4, none): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
```

It looks like the audio is able to download but the video was not. When I visit the URL it's trying to download the video from, it gives a 500 error. Could it be something with the deciphering?

I was able to download a lower quality format, but I'd really like to use the highest quality possible.

**Comment by 89z** [comment]
That is a DASH manifest video, so it might not be supported by this module

**Comment by Julian-Chu** [comment]
@89z  does your project already support DASH?

@uvanchang  , sorry , like mentioned above, this project doesn't support DASH now,  
  I tested [youtube-dl](https://github.com/ytdl-org/youtube-dl)  with this command `youtube-dl https://www.youtube.com/watch?v=K3MhYh29jwc  -f bestvideo+bestaudio.  It works properly.
`

**Comment by 89z** [comment]
> @89z does your project already support DASH?

Currently I just bail out on DASH videos [1], because handling them requires XML parsing. I didnt want to mess with writing an XML parser at the time, so I just left it out.

However Reddit also requires XML [2], so now that I wrote that, it wouldnt be too hard to add to YouTube as well. I havent seen many requests for the YouTube DASH videos, so I have been waiting. If enough people need it, then it would be worth adding. From my experience, very few videos are DASH, and I dont like adding features unless its really needed.

1. https://github.com/89z/mech/blob/v1.35.0/youtube/player.go#L46-L50
2. https://github.com/89z/mech/blob/v1.35.0/reddit/reddit.go#L42-L58

**Comment by uvanchang** [comment]
I will close then. Thanks for the info guys!

**Comment by 89z** [comment]
Hey, I found a DASH video that I actually care about:

https://www.youtube.com/watch?v=AQoYf5wY8o8

So I am interested in implementing this. I will try to get it done in a few days. I am really busy though, so if I dont post an update in a few days, you can remind me if you want.
