### ISSUE TITLE
panic: interface conversion: interface {} is nil, not map[string]interface {}

### ISSUE THREAD

**Issue by greentornado** [kkdai/youtube#65]
I got this error when trying this ID `9ja-K2FslBU`

**Comment by Julian-Chu** [comment]
hi @greentornado 
thank you for opening issue.

This issue is due to unavailable video , so status is "Error" which is not covered  in downloadable check.
https://www.youtube.com/watch?v=9ja-K2FslBU
![image](https://user-images.githubusercontent.com/7224544/86544026-00b7e100-bf24-11ea-875f-9844ee0b4ba6.png)

checking rule should be added.
